package Ex1_Market;/*
    EXERCISE:
    Create multiple user registration classes for the following user types:
      - Ex1_Market.Customer
      - Ex1_Market.Seller
      - Admin
    All classes inherit from a base class "Ex1_Market.User"
    Ex1_Market.User contains => fullName, dob, gender, id(generated by method) and getters for these fields

    Ex1_Market.Customer will have customerId, cash balance, buy method and active flag
    Ex1_Market.Seller will have sellerId, list of goods (boots) [once bought - the item is taken out of this list], revenue and active flag [boolean - active/not active]
    Admin will have adminId and assigned list of customers and sellers, also method to suspend seller or customer
    E.g.
    Main class called "Ex1_Market.Market" ==> [Customers, Sellers, Admins];
    Class Goods
    adminA.suspend(sellerId); or
    adminA.suspend(id, "seller");
    Check if active, check cash balance = if yes, remove from the list of goods; if no, notification
    customerA.buy(sellerId, productId);

 */
import Ex1_Market.enums.Gender;

import java.util.Date;
import java.util.Random;

public class User {
    private String fullName;
    private Date dob;
    private Gender gender;
    private Integer id;

    public int generateId(){
        Random random = new Random();
        return random.nextInt(900);
    }

    public String getFullName(){
        return fullName;
    }

    public Date getDob() {
        return dob;
    }

    public Gender getGender() {
        return gender;
    }

    public Integer getId() {
        return id;
    }

    public User(String fullName, Date dob, Gender gender){
        this.fullName = fullName;
        this.dob = dob;
        this.gender = gender;
        this.id = generateId();
    }
}