/*
    EXERCISE:
    Create multiple user registration classes for the following user types:
      - Customer
      - Seller
      - Admin
    All classes inherit from a base class "User"
    User contains => fullName, dob, gender, id(generated by method) and getters for these fields

    Customer will have customerId, cash balance, buy method and active flag
    Seller will have sellerId, list of goods (boots) [once bought - the item is taken out of this list], revenue and active flag [boolean - active/not active]
    Admin will have adminId and assigned list of customers and sellers, also method to suspend seller or customer
    E.g.
    Main class called "Market" ==> [Customers, Sellers, Admins];
    Class Goods
    adminA.suspend(sellerId); or
    adminA.suspend(id, "seller");
    Check if active, check cash balance = if yes, remove from the list of goods; if no, notification
    customerA.buy(sellerId, productId);

 */
import java.util.Random;

public class Exercise_1_UserRegistration {
    public static void main(String[] args) {

    }

    public abstract class User {

        protected String fullName;
        protected String gender;
        public void UserID(){

            Random random = new Random();
            int UserID = random.nextInt();
            System.out.println(UserID);

// read about the methods again + randomizer
            // setter and getter methods
        }

    }

    class Customer extends User {

    }

    class Seller extends User {

    }

    class Admin extends User {

    }


}
